# Generated by Django 4.2.2 on 2023-06-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('C', 'Cuarto'), ('DE', 'Departamento'), ('M', 'Monoblock'), ('DU', 'Duplex')], default='C', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbienteInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.ambiente')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.inquilino')),
            ],
        ),
    ]
