# Generated by Django 4.2.2 on 2023-06-30 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='libre',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='ServicioAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.ambiente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.servicio')),
            ],
        ),
    ]
